import { AffiliateProduct, AffiliateCategory } from "./types";

// Outcome-driven catalog: 20 products across 6 categories
// Naming rule: product name = what user achieves, not the platform
// CTA labels: action verbs ("Fix My Resume", "Start Free", not "Learn More")

export const CATALOG: AffiliateProduct[] = [
  // ─── COURSES (8 products) ──────────────────────────────────────────────────────

  {
    id: "python-job-ready",
    name: "Become Python Job-Ready in 30 Days",
    description: "Go from zero to confidently listing Python, Django, and data science on your resume — with projects you can show in interviews.",
    url: "https://click.linksynergy.com/deeplink?id=YOUR_ID&mid=39197&murl=https%3A%2F%2Fwww.udemy.com%2Fcourse%2Fcomplete-python-bootcamp",
    category: AffiliateCategory.COURSES,
    tags: ["python", "django", "flask", "fastapi", "data science", "pandas"],
    ctaLabel: "Start Learning Free",
    badge: "Most Popular",
    trustSignal: "Used by 1.2M+ learners worldwide",
    hookLabel: "Most-clicked by users missing Python",
    isHighIntent: true,
    payoutWeight: 0.6,
  },
  {
    id: "javascript-complete",
    name: "Add JavaScript to Your Skill Set — Fast",
    description: "Build real, portfolio-worthy projects in JavaScript and Node.js that recruiters recognise in under 30 days.",
    url: "https://click.linksynergy.com/deeplink?id=YOUR_ID&mid=39197&murl=https%3A%2F%2Fwww.udemy.com%2Fcourse%2Fthe-complete-javascript-course",
    category: AffiliateCategory.COURSES,
    tags: ["javascript", "node.js", "typescript", "es6"],
    ctaLabel: "Start Learning Free",
    payoutWeight: 0.55,
  },
  {
    id: "react-job-ready",
    name: "Master React and Land Frontend Roles",
    description: "Covers hooks, Redux, and Next.js — the exact React skills listed in 80% of frontend job descriptions.",
    url: "https://click.linksynergy.com/deeplink?id=YOUR_ID&mid=39197&murl=https%3A%2F%2Fwww.udemy.com%2Fcourse%2Freact-the-complete-guide",
    category: AffiliateCategory.COURSES,
    tags: ["react", "redux", "next.js", "typescript", "frontend"],
    ctaLabel: "Start Learning Free",
    badge: "Top Rated",
    trustSignal: "4.7★ from 180,000 students",
    payoutWeight: 0.6,
  },
  {
    id: "aws-certified",
    name: "Add AWS to Your Resume — Get Cloud-Certified",
    description: "The AWS Cloud Practitioner cert is the fastest way to unlock cloud roles and a 40% salary premium.",
    url: "https://www.udemy.com/course/aws-cloud-practitioner-essentials/",
    category: AffiliateCategory.COURSES,
    tags: ["aws", "cloud", "ec2", "s3", "lambda", "terraform"],
    ctaLabel: "Get AWS Certified",
    badge: "High Salary ROI",
    trustSignal: "Amazon's official certification path",
    isHighIntent: true,
    payoutWeight: 0.9,
  },
  {
    id: "sql-data-science",
    name: "Master SQL — The Skill Every Data Role Requires",
    description: "SQL is listed in 90% of data analyst and data science job descriptions. Add it in 2 weeks.",
    url: "https://www.coursera.org/learn/sql-for-data-science",
    category: AffiliateCategory.COURSES,
    tags: ["sql", "mysql", "postgresql", "database", "data analyst"],
    ctaLabel: "Learn SQL Free",
    isHighIntent: true,
    payoutWeight: 0.5,
  },
  {
    id: "data-science-cert",
    name: "Earn a Data Science Certificate That Gets Interviews",
    description: "IBM's 9-course program covers Python, ML, and real projects. Employers recognise this certificate.",
    url: "https://www.coursera.org/professional-certificates/ibm-data-science",
    category: AffiliateCategory.COURSES,
    tags: ["data science", "machine learning", "python", "pandas", "numpy", "ibm"],
    ctaLabel: "Start Certificate Free",
    badge: "Free Trial",
    trustSignal: "500,000+ completions on Coursera",
    payoutWeight: 0.7,
  },
  {
    id: "product-management",
    name: "Break Into Product Management — No Tech Degree Needed",
    description: "Learn roadmapping, agile, and the stakeholder skills that appear in every PM job description.",
    url: "https://www.linkedin.com/learning/become-a-product-manager",
    category: AffiliateCategory.COURSES,
    tags: ["product management", "agile", "jira", "roadmap", "product owner"],
    ctaLabel: "Explore Course",
    payoutWeight: 0.5,
  },
  {
    id: "pmp-cert",
    name: "Get PMP Certified and Boost Your Salary by $20k",
    description: "The PMP is the most recognised project management credential. Average salary lift: $20,000.",
    url: "https://www.udemy.com/course/pmp-exam-prep-course/",
    category: AffiliateCategory.COURSES,
    tags: ["project management", "pmp", "agile", "scrum", "waterfall"],
    ctaLabel: "Start PMP Prep",
    badge: "High Salary ROI",
    trustSignal: "Globally recognised by 250+ countries",
    isHighIntent: true,
    payoutWeight: 0.85,
  },

  // ─── RESUME_TOOLS (3 products) ─────────────────────────────────────────────────

  {
    id: "enhancv-resume",
    name: "Fix Your ATS Score — Rebuild Your Resume in 10 Minutes",
    description: "Most resumes are rejected by ATS before a human reads them. Enhancv is built specifically to pass ATS filters — no design skills needed, free to start.",
    url: "https://enhancv.com?ref=matchmyresumes",
    category: AffiliateCategory.RESUME_TOOLS,
    tags: ["resume builder", "ats", "formatting", "cv"],
    scoreGapTags: ["section_score", "formatting_score", "quantification_score"],
    ctaLabel: "Fix My Resume Free",
    badge: "Most Popular",
    trustSignal: "3M+ resumes built — loved by Fortune 500 job seekers",
    hookLabel: "Top fix for low ATS scores",
    isHighIntent: true,
    payoutWeight: 0.8,
  },
  {
    id: "canva-resume",
    name: "Design a Resume Recruiters Actually Remember",
    description: "Canva's ATS-safe resume templates take 15 minutes to complete and make your application stand out visually.",
    url: "https://www.canva.com/resumes/?ref=matchmyresumes",
    category: AffiliateCategory.RESUME_TOOLS,
    tags: ["resume builder", "templates", "design", "ats"],
    scoreGapTags: ["formatting_score", "content_density_score", "section_score"],
    ctaLabel: "Try Free Templates",
    badge: "Free",
    trustSignal: "100M+ users trust Canva",
    payoutWeight: 0.3,
  },
  {
    id: "resume-io",
    name: "Create a Complete, ATS-Safe Resume in 10 Minutes",
    description: "Resume.io guides you through every section so you never miss what ATS systems require. Start free.",
    url: "https://www.resume.io?ref=matchmyresumes",
    category: AffiliateCategory.RESUME_TOOLS,
    tags: ["resume builder", "ats", "cv", "templates"],
    scoreGapTags: ["formatting_score", "contact_score", "section_score"],
    ctaLabel: "Start Free",
    trustSignal: "10M+ resumes created",
    payoutWeight: 0.65,
  },

  // ─── INTERVIEW_PREP (3 products) ───────────────────────────────────────────────

  {
    id: "leetcode-premium",
    name: "Crack the Coding Interview at Top Companies",
    description: "Access company-specific LeetCode questions so you practice exactly what your target employer asks.",
    url: "https://leetcode.com/subscribe/?ref=matchmyresumes",
    category: AffiliateCategory.INTERVIEW_PREP,
    tags: ["algorithms", "data structures", "coding interview", "faang"],
    ctaLabel: "Practice Free",
    badge: "FAANG-Ready",
    trustSignal: "Used by engineers at Google, Meta, and Amazon",
    payoutWeight: 0.7,
  },
  {
    id: "pramp-mock",
    name: "Stop Freezing in Interviews — Practice Free in 1 Week",
    description: "Pramp pairs you with real engineers for live mock interviews. Book your first session free — no commitment, no credit card.",
    url: "https://www.pramp.com?ref=matchmyresumes",
    category: AffiliateCategory.INTERVIEW_PREP,
    tags: ["interview", "system design", "behavioral", "mock interview"],
    ctaLabel: "Book Free Mock — No Sign-Up Fee",
    badge: "Free Trial",
    trustSignal: "40,000+ interviews completed on Pramp",
    payoutWeight: 0.4,
  },
  {
    id: "interview-kickstart",
    name: "Land Offers at FAANG — With a Guarantee",
    description: "Interview Kickstart offers a refund if you don't get interviews at top companies. The most serious prep program available.",
    url: "https://www.interviewkickstart.com?ref=matchmyresumes",
    category: AffiliateCategory.INTERVIEW_PREP,
    tags: ["faang", "system design", "algorithms", "senior engineer"],
    ctaLabel: "See the Program",
    badge: "Top Rated",
    trustSignal: "Average offer: $250k+ total comp",
    isHighIntent: true,
    payoutWeight: 1.0,
  },

  // ─── LINKEDIN_TOOLS (2 products) ──────────────────────────────────────────────

  {
    id: "linkedin-premium",
    name: "Get Found by Recruiters — LinkedIn Premium Free for 1 Month",
    description: "Premium shows you where you rank among applicants and lets recruiters find you directly. Try free for 30 days.",
    url: "https://www.linkedin.com/premium/?ref=matchmyresumes",
    category: AffiliateCategory.LINKEDIN_TOOLS,
    tags: ["linkedin", "recruiter", "profile", "networking"],
    scoreGapTags: ["contact_score", "keyword_score", "semantic_score"],
    ctaLabel: "Try 1 Month Free",
    badge: "Free Trial",
    trustSignal: "Used by 65M+ professionals",
    payoutWeight: 0.75,
  },
  {
    id: "careerflow-linkedin",
    name: "Optimize Your LinkedIn to Match Every Job Description",
    description: "Careerflow scores your LinkedIn profile against job listings and tells you exactly what to fix.",
    url: "https://www.careerflow.ai?ref=matchmyresumes",
    category: AffiliateCategory.LINKEDIN_TOOLS,
    tags: ["linkedin", "profile", "keyword", "optimization"],
    scoreGapTags: ["contact_score", "keyword_score"],
    ctaLabel: "Try Free",
    trustSignal: "Recommended by 500+ career coaches",
    payoutWeight: 0.5,
  },

  // ─── CAREER_COACHING (2 products) ─────────────────────────────────────────────

  {
    id: "topmate-career",
    name: "Get Expert Resume Feedback in 30 Minutes",
    description: "Skip the guessing — book a 1:1 session with a senior recruiter or career coach who reviews resumes daily.",
    url: "https://topmate.io?ref=matchmyresumes",
    category: AffiliateCategory.CAREER_COACHING,
    tags: ["career", "mentorship", "resume review"],
    ctaLabel: "Book a Session",
    trustSignal: "10,000+ sessions booked by job seekers",
    payoutWeight: 0.6,
  },
  {
    id: "arc-remote",
    name: "Find Premium Remote Jobs With No Recruiter Spam",
    description: "Arc curates remote tech roles at vetted companies. Apply directly — no cold emails, no middlemen.",
    url: "https://arc.dev?ref=matchmyresumes",
    category: AffiliateCategory.JOB_BOARDS,
    tags: ["remote", "tech jobs", "developer jobs"],
    ctaLabel: "Browse Remote Jobs",
    payoutWeight: 0.4,
  },

  // ─── JOB_BOARDS (2 products) ──────────────────────────────────────────────────

  {
    id: "wellfound-jobs",
    name: "Get Hired at a Startup — No Recruiter Needed",
    description: "Wellfound (formerly AngelList) lets you apply directly to startups with salary ranges shown upfront.",
    url: "https://wellfound.com?ref=matchmyresumes",
    category: AffiliateCategory.JOB_BOARDS,
    tags: ["startup", "tech jobs", "equity"],
    ctaLabel: "Browse Jobs Free",
    payoutWeight: 0.25,
  },
  {
    id: "remoteok-jobs",
    name: "Find Remote Tech Jobs Updated Every Hour",
    description: "RemoteOK aggregates the freshest remote roles across engineering, design, and product. Filter by stack.",
    url: "https://remoteok.com?ref=matchmyresumes",
    category: AffiliateCategory.JOB_BOARDS,
    tags: ["remote", "tech jobs", "developer"],
    ctaLabel: "Search Jobs",
    payoutWeight: 0.2,
  },
];

// Page-context defaults — used when no strong recommendations exist
export const PAGE_CONTEXT_DEFAULTS: Record<string, string[]> = {
  "cv-analysis": ["enhancv-resume", "canva-resume"],
  "scan": ["python-job-ready", "linkedin-premium"],
  "optimize": ["enhancv-resume", "topmate-career"],
  "cover-letter": ["linkedin-premium", "pramp-mock"],
  "tracker": ["wellfound-jobs", "remoteok-jobs"],
  "marketing-ats": ["enhancv-resume", "canva-resume"],
  "marketing-jd": ["python-job-ready", "linkedin-premium"],
  "marketing-optimizer": ["enhancv-resume", "topmate-career"],
};
