export type ExperienceLevel = "fresher" | "mid" | "senior" | "executive"
export type TemplateCategory = "modern" | "simple" | "professional" | "fresher" | "tech" | "executive" | "career-change" | "creative"
export type FileFormat = "DOCX" | "PDF" | "Google Docs"

export interface ResumeTemplate {
  id: string
  name: string
  slug: string
  description: string
  category: TemplateCategory
  experienceLevel: ExperienceLevel[]
  formats: FileFormat[]
  fileName: string
  previewImage: string
  color: string
  downloads: number
}

export const CATEGORY_LABELS: Record<TemplateCategory, string> = {
  modern: "Modern ATS Resume",
  simple: "Simple ATS Resume",
  professional: "Professional Resume",
  fresher: "Fresher Resume",
  tech: "Tech Resume",
  executive: "Executive Resume",
  "career-change": "Career Changer",
  creative: "Creative Professional",
}

export const EXPERIENCE_LABELS: Record<ExperienceLevel, string> = {
  fresher: "Entry Level / Fresher",
  mid: "Mid Level (2-5 yrs)",
  senior: "Senior (5-10 yrs)",
  executive: "Executive (10+ yrs)",
}

export const templates: ResumeTemplate[] = [
  // Modern ATS Resume
  {
    id: "modern-clean",
    name: "Modern Clean",
    slug: "modern-clean-ats-resume-template",
    description: "A sleek, single-column layout with clean typography. Passes 98% of ATS parsers with optimized section headers.",
    category: "modern",
    experienceLevel: ["mid", "senior"],
    formats: ["DOCX", "PDF"],
    fileName: "modern-clean-ats-resume.docx",
    previewImage: "/images/templates/modern-clean.svg",
    color: "#6c5ce7",
    downloads: 12450,
  },
  {
    id: "modern-minimal",
    name: "Modern Minimal",
    slug: "modern-minimal-ats-resume-template",
    description: "Minimalist design with subtle accent lines. Zero-graphics layout ensures perfect ATS compatibility.",
    category: "modern",
    experienceLevel: ["mid", "senior"],
    formats: ["DOCX", "Google Docs"],
    fileName: "modern-minimal-ats-resume.docx",
    previewImage: "/images/templates/modern-minimal.svg",
    color: "#00b894",
    downloads: 9830,
  },
  {
    id: "modern-two-tone",
    name: "Modern Two-Tone",
    slug: "modern-two-tone-ats-resume-template",
    description: "Professional two-tone styling with a personal brand statement. Great for mid-career professionals who want to stand out.",
    category: "modern",
    experienceLevel: ["mid", "senior"],
    formats: ["DOCX", "PDF"],
    fileName: "modern-two-tone-ats-resume.docx",
    previewImage: "/images/templates/modern-two-tone.svg",
    color: "#34495e",
    downloads: 7650,
  },
  // Simple ATS Resume
  {
    id: "simple-classic",
    name: "Simple Classic",
    slug: "simple-classic-ats-resume-template",
    description: "Traditional resume format trusted by recruiters. Standard sections, clear hierarchy, maximum readability.",
    category: "simple",
    experienceLevel: ["fresher", "mid"],
    formats: ["DOCX", "PDF", "Google Docs"],
    fileName: "simple-classic-ats-resume.docx",
    previewImage: "/images/templates/simple-classic.svg",
    color: "#2d3436",
    downloads: 18200,
  },
  {
    id: "simple-one-column",
    name: "Simple One Column",
    slug: "simple-one-column-ats-resume-template",
    description: "Single-column format with generous spacing. Ideal for ATS parsing with zero formatting errors.",
    category: "simple",
    experienceLevel: ["fresher", "mid"],
    formats: ["DOCX", "PDF"],
    fileName: "simple-one-column-ats-resume.docx",
    previewImage: "/images/templates/simple-one-column.svg",
    color: "#636e72",
    downloads: 14500,
  },
  {
    id: "simple-elegant",
    name: "Simple Elegant",
    slug: "simple-elegant-ats-resume-template",
    description: "Centered header with understated elegance. Clean lines and balanced spacing for a polished, professional look.",
    category: "simple",
    experienceLevel: ["fresher", "mid", "senior"],
    formats: ["DOCX", "PDF"],
    fileName: "simple-elegant-ats-resume.docx",
    previewImage: "/images/templates/simple-elegant.svg",
    color: "#828282",
    downloads: 11300,
  },
  // Professional Resume
  {
    id: "professional-standard",
    name: "Professional Standard",
    slug: "professional-standard-ats-resume-template",
    description: "Industry-standard professional layout. Balanced white space, clear section dividers, ATS-optimized headings.",
    category: "professional",
    experienceLevel: ["mid", "senior"],
    formats: ["DOCX", "PDF"],
    fileName: "professional-standard-ats-resume.docx",
    previewImage: "/images/templates/professional-standard.svg",
    color: "#0984e3",
    downloads: 15700,
  },
  {
    id: "professional-corporate",
    name: "Corporate Professional",
    slug: "corporate-professional-ats-resume-template",
    description: "Designed for corporate roles. Structured sections for achievements, certifications, and leadership experience.",
    category: "professional",
    experienceLevel: ["senior", "executive"],
    formats: ["DOCX", "Google Docs"],
    fileName: "corporate-professional-ats-resume.docx",
    previewImage: "/images/templates/corporate-professional.svg",
    color: "#2d3436",
    downloads: 11200,
  },
  {
    id: "professional-chronological",
    name: "Chronological Professional",
    slug: "chronological-professional-ats-resume-template",
    description: "Reverse-chronological format emphasizing career progression. Ideal for professionals with steady upward growth.",
    category: "professional",
    experienceLevel: ["mid", "senior", "executive"],
    formats: ["DOCX", "PDF"],
    fileName: "chronological-professional-ats-resume.docx",
    previewImage: "/images/templates/chronological-professional.svg",
    color: "#006400",
    downloads: 13400,
  },
  // Fresher Resume
  {
    id: "fresher-graduate",
    name: "Fresh Graduate",
    slug: "fresh-graduate-ats-resume-template",
    description: "Built for recent graduates. Highlights education, projects, internships, and skills over work experience.",
    category: "fresher",
    experienceLevel: ["fresher"],
    formats: ["DOCX", "PDF", "Google Docs"],
    fileName: "fresh-graduate-ats-resume.docx",
    previewImage: "/images/templates/fresh-graduate.svg",
    color: "#e17055",
    downloads: 22100,
  },
  {
    id: "fresher-internship",
    name: "Internship Ready",
    slug: "internship-ready-ats-resume-template",
    description: "Optimized for internship applications. Showcases coursework, projects, and extracurriculars effectively.",
    category: "fresher",
    experienceLevel: ["fresher"],
    formats: ["DOCX", "PDF"],
    fileName: "internship-ready-ats-resume.docx",
    previewImage: "/images/templates/internship-ready.svg",
    color: "#fdcb6e",
    downloads: 16800,
  },
  // Tech Resume
  {
    id: "tech-developer",
    name: "Software Developer",
    slug: "software-developer-ats-resume-template",
    description: "Tailored for software engineers. Dedicated sections for tech stack, projects, and GitHub contributions.",
    category: "tech",
    experienceLevel: ["mid", "senior"],
    formats: ["DOCX", "PDF"],
    fileName: "software-developer-ats-resume.docx",
    previewImage: "/images/templates/software-developer.svg",
    color: "#6c5ce7",
    downloads: 19500,
  },
  {
    id: "tech-data-science",
    name: "Data Science",
    slug: "data-science-ats-resume-template",
    description: "Purpose-built for data roles. Sections for tools, methodologies, publications, and quantified project outcomes.",
    category: "tech",
    experienceLevel: ["mid", "senior"],
    formats: ["DOCX", "Google Docs"],
    fileName: "data-science-ats-resume.docx",
    previewImage: "/images/templates/data-science.svg",
    color: "#00b894",
    downloads: 13200,
  },
  {
    id: "tech-devops",
    name: "DevOps Engineer",
    slug: "devops-engineer-ats-resume-template",
    description: "Infrastructure-focused template with dedicated sections for cloud platforms, CI/CD, IaC tools, and uptime metrics.",
    category: "tech",
    experienceLevel: ["mid", "senior"],
    formats: ["DOCX", "PDF"],
    fileName: "devops-engineer-ats-resume.docx",
    previewImage: "/images/templates/devops-engineer.svg",
    color: "#e67e22",
    downloads: 10800,
  },
  {
    id: "tech-product-manager",
    name: "Product Manager",
    slug: "product-manager-ats-resume-template",
    description: "Built for PMs. Highlights product strategy, user metrics, A/B testing outcomes, and cross-functional leadership.",
    category: "tech",
    experienceLevel: ["mid", "senior"],
    formats: ["DOCX", "PDF"],
    fileName: "product-manager-ats-resume.docx",
    previewImage: "/images/templates/product-manager.svg",
    color: "#8e44ad",
    downloads: 12100,
  },
  // Executive Resume
  {
    id: "executive-leadership",
    name: "Executive Leadership",
    slug: "executive-leadership-ats-resume-template",
    description: "C-suite and VP-level template. Emphasizes strategic impact, P&L ownership, and board-level achievements.",
    category: "executive",
    experienceLevel: ["executive"],
    formats: ["DOCX", "PDF"],
    fileName: "executive-leadership-ats-resume.docx",
    previewImage: "/images/templates/executive-leadership.svg",
    color: "#2d3436",
    downloads: 8400,
  },
  {
    id: "executive-senior-manager",
    name: "Senior Manager",
    slug: "senior-manager-ats-resume-template",
    description: "For directors and senior managers. Structured to highlight team leadership, KPIs, and cross-functional impact.",
    category: "executive",
    experienceLevel: ["senior", "executive"],
    formats: ["DOCX", "PDF", "Google Docs"],
    fileName: "senior-manager-ats-resume.docx",
    previewImage: "/images/templates/senior-manager.svg",
    color: "#0984e3",
    downloads: 10600,
  },
  {
    id: "executive-vp",
    name: "Executive VP",
    slug: "executive-vp-ats-resume-template",
    description: "VP/SVP/EVP template focused on transformation leadership, team scaling, and multi-million dollar P&L management.",
    category: "executive",
    experienceLevel: ["executive"],
    formats: ["DOCX", "PDF"],
    fileName: "executive-vp-ats-resume.docx",
    previewImage: "/images/templates/executive-vp.svg",
    color: "#2c3e50",
    downloads: 6900,
  },
  // Career Changer
  {
    id: "career-changer",
    name: "Career Changer",
    slug: "career-changer-ats-resume-template",
    description: "Designed for career transitions. Leads with transferable skills, relevant training, and projects in your new field.",
    category: "career-change",
    experienceLevel: ["mid", "senior"],
    formats: ["DOCX", "PDF"],
    fileName: "career-changer-ats-resume.docx",
    previewImage: "/images/templates/career-changer.svg",
    color: "#993300",
    downloads: 14200,
  },
  // Creative Professional
  {
    id: "creative-professional",
    name: "Creative Professional",
    slug: "creative-professional-ats-resume-template",
    description: "For designers, content creators, and UX professionals. Portfolio-ready with sections for awards and selected projects.",
    category: "creative",
    experienceLevel: ["mid", "senior"],
    formats: ["DOCX", "PDF"],
    fileName: "creative-professional-ats-resume.docx",
    previewImage: "/images/templates/creative-professional.svg",
    color: "#c0392b",
    downloads: 9500,
  },
]
