export interface ResumeExample {
  slug: string
  title: string
  category: string
  description: string
  keywords: string[]
  summary: string
  experienceBullets: string[]
  skills: string[]
  education: string
  certifications: string[]
  tips: string[]
  faqs: { q: string; a: string }[]
}

export const resumeExamples: ResumeExample[] = [
  {
    slug: "software-engineer",
    title: "Software Engineer",
    category: "Technology",
    description:
      "Software engineer resume example with ATS-optimized keywords, strong achievement bullets, and technical skills. Get hired at top tech companies in 2026.",
    keywords: [
      "software development",
      "agile methodology",
      "REST APIs",
      "CI/CD",
      "code review",
      "system design",
      "unit testing",
      "microservices",
      "cloud computing",
      "version control",
    ],
    summary:
      "Results-driven software engineer with 5+ years of experience designing and shipping scalable web applications. Proficient in TypeScript, Python, and cloud-native architectures, with a track record of reducing system latency by 40% and mentoring junior developers.",
    experienceBullets: [
      "Architected and deployed a microservices platform serving 2M+ daily requests, reducing infrastructure costs by 35%",
      "Led migration from monolith to event-driven architecture, improving deployment frequency from biweekly to daily",
      "Implemented automated CI/CD pipelines that cut release cycle time by 60% and eliminated manual deployment errors",
      "Mentored 4 junior engineers through code reviews and pair programming, accelerating their onboarding by 50%",
      "Optimized database queries and caching layer, reducing average API response time from 450ms to 120ms",
    ],
    skills: [
      "TypeScript",
      "Python",
      "React",
      "Node.js",
      "AWS",
      "Docker",
      "PostgreSQL",
      "Redis",
      "GraphQL",
      "Kubernetes",
      "Git",
      "Terraform",
    ],
    education: "Bachelor's in Computer Science",
    certifications: [
      "AWS Certified Solutions Architect",
      "Certified Kubernetes Administrator",
    ],
    tips: [
      "Quantify your impact — include metrics like latency reduction, cost savings, or user growth in every bullet point.",
      "List programming languages and frameworks in a dedicated skills section so ATS parsers can extract them easily.",
      "Tailor your resume to each job description by mirroring the exact technologies and methodologies mentioned.",
      "Include links to your GitHub profile or portfolio projects to demonstrate hands-on coding ability.",
    ],
    faqs: [
      {
        q: "How long should a software engineer resume be?",
        a: "One page is ideal for under 10 years of experience. Senior engineers with 10+ years can use two pages, but keep every bullet relevant and achievement-oriented.",
      },
      {
        q: "Should I list every programming language I know?",
        a: "No. Focus on languages and frameworks listed in the job description. Group secondary skills under a separate 'Familiar With' section to avoid diluting your core strengths.",
      },
      {
        q: "Do I need a summary section on a software engineer resume?",
        a: "Yes — a 2-3 sentence summary helps recruiters immediately see your experience level, core technologies, and biggest accomplishment. It also feeds ATS keyword matching.",
      },
    ],
  },
  {
    slug: "data-analyst",
    title: "Data Analyst",
    category: "Data & Analytics",
    description:
      "Data analyst resume example with ATS keywords, SQL expertise, and data visualization achievements. Stand out with metrics-driven bullet points.",
    keywords: [
      "data analysis",
      "SQL",
      "data visualization",
      "Python",
      "Tableau",
      "statistical analysis",
      "ETL",
      "business intelligence",
      "A/B testing",
      "reporting",
    ],
    summary:
      "Detail-oriented data analyst with 4+ years of experience transforming raw data into actionable business insights. Skilled in SQL, Python, and Tableau, with a proven ability to reduce reporting time by 70% and drive $2M+ in revenue through data-driven recommendations.",
    experienceBullets: [
      "Built automated dashboards in Tableau that replaced 15+ manual Excel reports, saving the team 20 hours per week",
      "Designed and executed A/B tests that increased conversion rates by 18%, contributing $2.1M in incremental annual revenue",
      "Developed ETL pipelines processing 5M+ records daily with 99.9% accuracy using Python and Apache Airflow",
      "Partnered with product and marketing teams to define KPIs and deliver weekly insights that shaped go-to-market strategy",
      "Created a customer segmentation model that improved email campaign targeting, lifting open rates by 32%",
    ],
    skills: [
      "SQL",
      "Python",
      "Tableau",
      "Power BI",
      "Excel",
      "R",
      "Apache Airflow",
      "Snowflake",
      "Google Analytics",
      "Looker",
      "Statistical Modeling",
      "Data Warehousing",
    ],
    education: "Bachelor's in Statistics",
    certifications: [
      "Google Data Analytics Professional Certificate",
      "Tableau Desktop Specialist",
      "Microsoft Certified: Data Analyst Associate",
    ],
    tips: [
      "Highlight the business impact of your analyses — revenue generated, costs saved, or efficiency gains — not just the tools you used.",
      "Showcase your SQL proficiency prominently; it appears in nearly every data analyst job listing.",
      "Include a mix of technical skills (Python, SQL) and soft skills (stakeholder communication, storytelling with data).",
      "Mention specific data volumes you've worked with to demonstrate your ability to handle scale.",
    ],
    faqs: [
      {
        q: "What technical skills should a data analyst resume include?",
        a: "SQL is essential. Also include Python or R, at least one visualization tool (Tableau, Power BI), spreadsheet expertise, and any cloud data warehouse experience (Snowflake, BigQuery).",
      },
      {
        q: "How do I show impact if my work is mainly reporting?",
        a: "Frame reports as decision-enablers: 'Built executive dashboard that surfaced a $500K cost-saving opportunity' is far stronger than 'Created weekly reports for leadership.'",
      },
      {
        q: "Should I include personal data projects on my resume?",
        a: "Yes, especially if you're early in your career. Kaggle competitions, personal dashboards, or open-source contributions demonstrate initiative and practical skills.",
      },
    ],
  },
  {
    slug: "registered-nurse",
    title: "Registered Nurse",
    category: "Healthcare",
    description:
      "Registered nurse resume example with clinical keywords, patient care achievements, and certifications. ATS-optimized for hospital and healthcare roles.",
    keywords: [
      "patient care",
      "electronic health records",
      "clinical assessment",
      "medication administration",
      "care planning",
      "HIPAA compliance",
      "patient education",
      "vital signs monitoring",
      "interdisciplinary collaboration",
      "infection control",
    ],
    summary:
      "Compassionate registered nurse with 6+ years of experience in acute care and emergency settings. Proven ability to manage 8+ patients simultaneously while maintaining 98% patient satisfaction scores and zero medication errors over 3 consecutive years.",
    experienceBullets: [
      "Provided comprehensive care for 8-12 patients per shift in a 40-bed medical-surgical unit with 98% satisfaction scores",
      "Reduced hospital-acquired infection rates by 25% through implementation of evidence-based hand hygiene protocols",
      "Trained and mentored 10+ new graduate nurses, decreasing orientation period from 12 weeks to 8 weeks",
      "Collaborated with interdisciplinary team to develop care plans that reduced average patient length of stay by 1.2 days",
      "Maintained zero medication errors over 36 consecutive months through rigorous double-check protocols",
    ],
    skills: [
      "Patient Assessment",
      "IV Therapy",
      "EHR (Epic, Cerner)",
      "Wound Care",
      "Medication Administration",
      "Patient Education",
      "Critical Thinking",
      "BLS/ACLS",
      "Care Coordination",
      "Telemetry Monitoring",
      "Infection Control",
      "Triage",
    ],
    education: "Bachelor of Science in Nursing (BSN)",
    certifications: [
      "Registered Nurse (RN) License",
      "BLS/ACLS Certified",
      "CCRN – Critical Care Registered Nurse",
    ],
    tips: [
      "Always list your active nursing license and state at the top of your resume — recruiters check this first.",
      "Use clinical terminology that matches the job posting (e.g., 'telemetry monitoring' not 'heart monitoring').",
      "Quantify patient loads, satisfaction scores, and safety metrics to stand out from other applicants.",
      "Include EHR systems you've used (Epic, Cerner, Meditech) — these are common ATS keywords.",
    ],
    faqs: [
      {
        q: "Should I put my nursing license number on my resume?",
        a: "List your license type, state, and expiration date. Including your license number is optional — some nurses omit it for privacy and provide it upon request.",
      },
      {
        q: "How do I make my nursing resume stand out?",
        a: "Focus on measurable outcomes: patient satisfaction scores, infection rate reductions, and efficiency improvements. Generic descriptions like 'provided patient care' won't differentiate you.",
      },
      {
        q: "Do I need a BSN to get hired?",
        a: "Many hospitals prefer BSN-prepared nurses, but ADN nurses can still get hired. If you're pursuing your BSN, mention it as 'BSN in progress, expected completion [date].'",
      },
    ],
  },
  {
    slug: "marketing-manager",
    title: "Marketing Manager",
    category: "Marketing",
    description:
      "Marketing manager resume example with campaign metrics, digital marketing keywords, and leadership achievements. ATS-optimized for senior marketing roles.",
    keywords: [
      "digital marketing",
      "campaign management",
      "SEO/SEM",
      "content strategy",
      "marketing analytics",
      "brand management",
      "lead generation",
      "marketing automation",
      "budget management",
      "cross-functional leadership",
    ],
    summary:
      "Strategic marketing manager with 7+ years of experience driving brand growth through integrated digital campaigns. Led a team of 8 marketers to achieve 150% year-over-year lead generation growth while reducing cost-per-acquisition by 40%.",
    experienceBullets: [
      "Managed $1.2M annual marketing budget across paid, organic, and event channels, achieving 4.5x ROI",
      "Led rebranding initiative that increased brand awareness by 60% and website traffic by 85% within 6 months",
      "Built and scaled a content marketing program generating 3,000+ qualified leads per month from organic search",
      "Implemented marketing automation workflows in HubSpot that improved lead nurturing conversion by 35%",
      "Directed a team of 8 across content, design, and demand gen, consistently exceeding quarterly pipeline targets by 20%",
    ],
    skills: [
      "Google Analytics",
      "HubSpot",
      "SEO/SEM",
      "Content Strategy",
      "Paid Media",
      "Social Media Marketing",
      "Email Marketing",
      "A/B Testing",
      "Budget Management",
      "Team Leadership",
      "Salesforce",
      "Marketing Automation",
    ],
    education: "Bachelor's in Marketing",
    certifications: [
      "Google Ads Certification",
      "HubSpot Inbound Marketing Certification",
    ],
    tips: [
      "Lead with revenue impact and ROI metrics — marketing leaders are judged on pipeline contribution and cost efficiency.",
      "Specify the marketing tech stack you've used (HubSpot, Marketo, Salesforce) as these are heavily searched ATS keywords.",
      "Demonstrate both strategic thinking (budget allocation, brand positioning) and hands-on execution (campaign launches, A/B tests).",
      "Include team size and cross-functional collaboration to show leadership capability.",
    ],
    faqs: [
      {
        q: "How should I structure a marketing manager resume?",
        a: "Lead with a summary highlighting your biggest revenue or growth achievement. Follow with experience (most recent first), skills, and education. Keep it to one page unless you have 10+ years of experience.",
      },
      {
        q: "What metrics should I include on a marketing resume?",
        a: "Include ROI, cost-per-acquisition, lead volume, conversion rates, traffic growth, and revenue influenced. Every bullet should have at least one number.",
      },
      {
        q: "Should I include freelance or consulting marketing work?",
        a: "Yes, especially if you achieved measurable results. List it under a 'Consulting' or 'Freelance' header with the same achievement-focused format as full-time roles.",
      },
    ],
  },
  {
    slug: "project-manager",
    title: "Project Manager",
    category: "Management",
    description:
      "Project manager resume example with Agile/PMP keywords, budget management achievements, and stakeholder communication. ATS-ready for PM roles.",
    keywords: [
      "project management",
      "Agile/Scrum",
      "risk management",
      "stakeholder management",
      "budget tracking",
      "resource allocation",
      "cross-functional teams",
      "project lifecycle",
      "milestone tracking",
      "change management",
    ],
    summary:
      "PMP-certified project manager with 8+ years of experience delivering complex cross-functional projects on time and under budget. Managed portfolios valued at $15M+ and led teams of up to 25 members across 4 time zones.",
    experienceBullets: [
      "Delivered 30+ projects with a combined budget of $15M, completing 95% on time and 100% within budget",
      "Led Agile transformation for a 50-person engineering team, increasing sprint velocity by 40% within two quarters",
      "Implemented risk management framework that identified and mitigated 85% of potential blockers before they impacted timelines",
      "Managed cross-functional stakeholder communication across engineering, design, and business teams in 4 time zones",
      "Reduced project overhead costs by 22% through optimized resource allocation and vendor renegotiations",
    ],
    skills: [
      "Agile/Scrum",
      "Waterfall",
      "Jira",
      "Microsoft Project",
      "Risk Management",
      "Budgeting",
      "Stakeholder Communication",
      "Resource Planning",
      "Confluence",
      "Gantt Charts",
      "OKRs",
      "Vendor Management",
    ],
    education: "Bachelor's in Business Administration",
    certifications: [
      "PMP – Project Management Professional",
      "Certified ScrumMaster (CSM)",
      "PRINCE2 Practitioner",
    ],
    tips: [
      "Include your PMP or CSM certification prominently — many recruiters filter for these credentials first.",
      "Quantify project scope with budget size, team size, and timeline to demonstrate the scale of your experience.",
      "Highlight both methodologies you've used (Agile, Waterfall, hybrid) and tools (Jira, MS Project, Asana).",
      "Show stakeholder management skills — PMs are judged on communication as much as delivery.",
    ],
    faqs: [
      {
        q: "Is PMP certification required for project manager roles?",
        a: "Not always, but it significantly increases your chances. Many enterprise companies require PMP for senior PM roles. If you're working toward it, add 'PMP in progress' to your resume.",
      },
      {
        q: "How do I describe failed or cancelled projects?",
        a: "Focus on what you learned and how you applied those lessons. For example: 'Identified scope creep early and recommended project pivot, saving $200K in sunk costs.'",
      },
      {
        q: "Should I list technical skills as a project manager?",
        a: "Yes — list PM tools (Jira, Asana), methodologies (Agile, PRINCE2), and any domain-specific technical knowledge. Technical PMs should also include relevant technologies they manage.",
      },
    ],
  },
  {
    slug: "graphic-designer",
    title: "Graphic Designer",
    category: "Design",
    description:
      "Graphic designer resume example with creative portfolio highlights, design tool keywords, and branding achievements. ATS-optimized for design roles.",
    keywords: [
      "graphic design",
      "Adobe Creative Suite",
      "brand identity",
      "typography",
      "visual design",
      "print design",
      "digital design",
      "layout design",
      "color theory",
      "design systems",
    ],
    summary:
      "Creative graphic designer with 5+ years of experience crafting visual identities for B2B and consumer brands. Designed brand systems adopted by 200+ franchise locations and increased social media engagement by 120% through compelling visual content.",
    experienceBullets: [
      "Designed complete brand identity system for a $50M franchise, including logo, typography, and style guide adopted by 200+ locations",
      "Created digital and print marketing collateral that contributed to a 45% increase in qualified leads over 12 months",
      "Increased social media engagement by 120% through original graphic content across Instagram, LinkedIn, and Twitter",
      "Collaborated with UX team to redesign company website, improving user retention by 30% and reducing bounce rate by 25%",
      "Managed a library of 500+ design assets and established a component-based design system that cut production time by 40%",
    ],
    skills: [
      "Adobe Photoshop",
      "Adobe Illustrator",
      "Adobe InDesign",
      "Figma",
      "Brand Identity",
      "Typography",
      "Print Production",
      "Motion Graphics",
      "After Effects",
      "Color Theory",
      "Layout Design",
      "Design Systems",
    ],
    education: "Bachelor of Fine Arts in Graphic Design",
    certifications: [
      "Adobe Certified Professional",
      "Google UX Design Certificate",
    ],
    tips: [
      "Always include a link to your online portfolio — design is a visual discipline and recruiters need to see your work.",
      "List specific Adobe tools (Photoshop, Illustrator, InDesign) separately rather than just 'Adobe Creative Suite' for better ATS matching.",
      "Quantify your design impact with engagement rates, conversion improvements, or production efficiency gains.",
      "Mention collaboration with other departments (marketing, product, engineering) to show you're a team player.",
    ],
    faqs: [
      {
        q: "Should I use a creative resume layout as a graphic designer?",
        a: "Use a clean, well-designed layout but keep it ATS-friendly. Fancy columns and graphics can confuse ATS parsers. Show your creativity in your portfolio instead.",
      },
      {
        q: "How important is a portfolio vs. a resume for designers?",
        a: "Both are essential. The resume gets you past ATS filters and HR screens; the portfolio convinces hiring managers. Include a portfolio link prominently on your resume.",
      },
      {
        q: "Should I include freelance design work?",
        a: "Absolutely. Freelance work shows initiative, client management skills, and versatility. List notable clients or projects with measurable outcomes.",
      },
    ],
  },
  {
    slug: "financial-analyst",
    title: "Financial Analyst",
    category: "Finance",
    description:
      "Financial analyst resume example with modeling keywords, forecasting achievements, and Excel expertise. ATS-optimized for finance and banking roles.",
    keywords: [
      "financial modeling",
      "forecasting",
      "variance analysis",
      "budgeting",
      "Excel",
      "financial reporting",
      "data analysis",
      "valuation",
      "P&L management",
      "risk assessment",
    ],
    summary:
      "Analytical financial analyst with 4+ years of experience in FP&A and corporate finance. Built financial models that guided $50M+ in capital allocation decisions and improved forecasting accuracy from 82% to 96%.",
    experienceBullets: [
      "Built 3-statement financial models supporting $50M+ in capital allocation and M&A due diligence decisions",
      "Improved quarterly revenue forecasting accuracy from 82% to 96% through enhanced statistical modeling techniques",
      "Automated monthly financial reporting using VBA and Power BI, reducing close cycle from 10 days to 4 days",
      "Conducted variance analysis across 12 business units, identifying $3.2M in cost-saving opportunities",
      "Presented financial insights to C-suite executives, influencing strategic decisions on pricing and market expansion",
    ],
    skills: [
      "Excel (Advanced)",
      "Financial Modeling",
      "Power BI",
      "SQL",
      "VBA",
      "Bloomberg Terminal",
      "SAP",
      "Forecasting",
      "Variance Analysis",
      "DCF Valuation",
      "Budget Management",
      "Pivot Tables",
    ],
    education: "Bachelor's in Finance",
    certifications: [
      "CFA Level II Candidate",
      "Financial Modeling & Valuation Analyst (FMVA)",
    ],
    tips: [
      "Highlight your Excel proficiency with specifics — mention VBA, pivot tables, VLOOKUP/INDEX-MATCH, and financial modeling.",
      "Quantify the dollar value of decisions your analyses influenced to show strategic impact.",
      "Include any CFA progress — even 'CFA Level I Passed' signals commitment to the profession.",
      "Mention specific financial tools and ERP systems (SAP, Oracle, Bloomberg) for ATS matching.",
    ],
    faqs: [
      {
        q: "Do I need a CFA for financial analyst roles?",
        a: "Not for entry-level roles, but it's increasingly preferred for mid-senior positions. Mention any CFA progress (Level I Passed, Level II Candidate) on your resume.",
      },
      {
        q: "How technical should a financial analyst resume be?",
        a: "Very. Include specific tools (Excel, SQL, Power BI), modeling techniques (DCF, LBO), and any programming languages. Finance is increasingly data-driven.",
      },
      {
        q: "Should I include GPA on a financial analyst resume?",
        a: "Include it if it's 3.5+ and you graduated within the last 3 years. For experienced analysts, GPA is less relevant — focus on work achievements instead.",
      },
    ],
  },
  {
    slug: "teacher",
    title: "Teacher",
    category: "Education",
    description:
      "Teacher resume example with classroom management keywords, student achievement metrics, and curriculum design experience. ATS-optimized for K-12 education roles.",
    keywords: [
      "curriculum development",
      "classroom management",
      "differentiated instruction",
      "student assessment",
      "lesson planning",
      "IEP",
      "parent communication",
      "educational technology",
      "state standards",
      "student engagement",
    ],
    summary:
      "Dedicated K-8 teacher with 6+ years of experience raising student proficiency by 30% through differentiated instruction and data-driven lesson planning. Recognized as Teacher of the Year for implementing innovative STEM curriculum adopted district-wide.",
    experienceBullets: [
      "Raised student math proficiency scores by 30% over two academic years through targeted small-group intervention",
      "Designed and implemented STEM curriculum adopted by 8 schools district-wide, reaching 2,400+ students annually",
      "Managed inclusive classrooms of 28+ students, including 6 IEP students, maintaining 95% parent satisfaction rating",
      "Integrated educational technology (Google Classroom, Kahoot, Nearpod) increasing student engagement scores by 40%",
      "Mentored 5 student teachers and led professional development workshops on differentiated instruction for 50+ faculty",
    ],
    skills: [
      "Curriculum Design",
      "Classroom Management",
      "Differentiated Instruction",
      "IEP Implementation",
      "Google Classroom",
      "Assessment Design",
      "Parent Communication",
      "STEM Education",
      "Data-Driven Instruction",
      "Behavioral Management",
      "EdTech Integration",
      "State Standards Alignment",
    ],
    education: "Master's in Education",
    certifications: [
      "State Teaching License (K-8)",
      "ESL/TESOL Endorsement",
      "Google Certified Educator",
    ],
    tips: [
      "Include your teaching license type, grade levels, and subject endorsements prominently — these are hard requirements.",
      "Quantify student outcomes with test score improvements, graduation rates, or proficiency gains.",
      "List educational technology platforms you've used — ed-tech fluency is increasingly important in job postings.",
      "Mention any curriculum you've designed or professional development you've led to show leadership.",
    ],
    faqs: [
      {
        q: "How long should a teacher resume be?",
        a: "One page for early-career teachers (0-5 years). Two pages are acceptable for experienced teachers with extensive curriculum development, leadership roles, or publications.",
      },
      {
        q: "Should I include volunteer tutoring or coaching on my resume?",
        a: "Yes — extracurricular involvement shows dedication to student development beyond the classroom. Include coaching, club sponsorship, and after-school programs.",
      },
      {
        q: "How do I handle gaps if I left teaching temporarily?",
        a: "Be honest. Many teachers take breaks for family, further education, or career exploration. Highlight any transferable skills gained (tutoring, corporate training, volunteer work).",
      },
    ],
  },
  {
    slug: "sales-representative",
    title: "Sales Representative",
    category: "Management",
    description:
      "Sales representative resume example with quota achievement metrics, CRM keywords, and prospecting achievements. ATS-optimized for B2B and B2C sales roles.",
    keywords: [
      "sales quota",
      "lead generation",
      "CRM",
      "pipeline management",
      "cold calling",
      "consultative selling",
      "account management",
      "negotiation",
      "revenue growth",
      "client relationship management",
    ],
    summary:
      "High-performing sales representative with 5+ years of B2B SaaS experience, consistently exceeding quota by 130%+. Generated $4.2M in new annual recurring revenue and built a client portfolio of 60+ enterprise accounts.",
    experienceBullets: [
      "Exceeded annual sales quota by 135% for 3 consecutive years, generating $4.2M in new ARR",
      "Built and managed a pipeline of $12M+ through targeted outbound prospecting and strategic networking",
      "Closed the company's largest enterprise deal ($850K ARR) through a 6-month consultative sales process",
      "Reduced sales cycle length by 20% by implementing a qualification framework that improved lead-to-close conversion by 35%",
      "Onboarded and mentored 6 new sales reps, with 5 of 6 achieving quota within their first quarter",
    ],
    skills: [
      "Salesforce",
      "HubSpot CRM",
      "Cold Outreach",
      "Pipeline Management",
      "Consultative Selling",
      "Contract Negotiation",
      "Account Management",
      "Sales Forecasting",
      "LinkedIn Sales Navigator",
      "Demo Presentations",
      "Objection Handling",
      "Territory Planning",
    ],
    education: "Bachelor's in Business Administration",
    certifications: [
      "Salesforce Certified Administrator",
      "HubSpot Sales Software Certification",
    ],
    tips: [
      "Lead every bullet with a number — quota attainment percentage, revenue generated, deals closed, or pipeline built.",
      "Name the CRM systems you've used (Salesforce, HubSpot) — these are critical ATS keywords for sales roles.",
      "Highlight your sales methodology experience (MEDDIC, Challenger, SPIN) if relevant to the target company.",
      "Include both hunting (new business) and farming (account expansion) achievements if applicable.",
    ],
    faqs: [
      {
        q: "How do I write a sales resume if I haven't hit quota?",
        a: "Focus on growth trajectory, specific deals won, and skills developed. You can mention 'ranked top 30% of sales team' or highlight quarters where you did exceed targets.",
      },
      {
        q: "Should I include my exact commission earnings?",
        a: "Include revenue generated and quota attainment percentages, but not personal compensation. 'Generated $2M in ARR (135% of quota)' is effective and professional.",
      },
      {
        q: "Is a cover letter important for sales roles?",
        a: "Yes — a cover letter is your first 'sales pitch' to the hiring manager. Use it to show your communication skills and explain why you're excited about their specific product or market.",
      },
    ],
  },
  {
    slug: "product-manager",
    title: "Product Manager",
    category: "Technology",
    description:
      "Product manager resume example with product strategy keywords, feature launch metrics, and cross-functional leadership. ATS-optimized for PM roles at tech companies.",
    keywords: [
      "product strategy",
      "roadmap planning",
      "user research",
      "A/B testing",
      "agile development",
      "PRD",
      "stakeholder management",
      "go-to-market",
      "product analytics",
      "feature prioritization",
    ],
    summary:
      "Data-driven product manager with 6+ years of experience shipping features used by 5M+ users. Led the 0-to-1 launch of a mobile product that generated $8M in first-year revenue and achieved 4.7-star app store rating.",
    experienceBullets: [
      "Led 0-to-1 development and launch of a mobile product generating $8M in first-year revenue with 500K+ downloads",
      "Defined and executed product roadmap for a $30M ARR platform, prioritizing features using RICE framework and user research",
      "Ran 40+ A/B experiments per quarter, increasing core conversion funnel by 28% and reducing churn by 15%",
      "Managed cross-functional team of 12 (engineering, design, data) through bi-weekly sprints with 92% on-time delivery rate",
      "Conducted 100+ user interviews and synthesized insights into PRDs that reduced feature iteration cycles by 35%",
    ],
    skills: [
      "Product Roadmapping",
      "Jira",
      "Amplitude",
      "Mixpanel",
      "SQL",
      "A/B Testing",
      "User Research",
      "PRD Writing",
      "Figma",
      "Agile/Scrum",
      "Stakeholder Management",
      "Go-to-Market Strategy",
    ],
    education: "Bachelor's in Computer Science, MBA",
    certifications: [
      "Pragmatic Institute Certified Product Manager",
      "Certified Scrum Product Owner (CSPO)",
    ],
    tips: [
      "Frame every achievement around user or business outcomes, not features shipped — PMs are judged on impact, not output.",
      "Include analytics tools (Amplitude, Mixpanel) and methodologies (A/B testing, user interviews) as these are key PM ATS keywords.",
      "Demonstrate both strategic thinking (vision, roadmap) and tactical execution (sprint planning, PRDs).",
      "If you transitioned into PM from engineering or design, highlight that cross-functional background as a strength.",
    ],
    faqs: [
      {
        q: "Do I need a technical background to be a product manager?",
        a: "Not necessarily, but technical fluency helps. Highlight any technical skills (SQL, basic coding, API understanding) and emphasize your ability to collaborate effectively with engineering teams.",
      },
      {
        q: "How do I write a PM resume with no PM title?",
        a: "Focus on PM-adjacent responsibilities: defining requirements, prioritizing features, analyzing data, or leading cross-functional projects. Many PMs transition from engineering, design, or consulting.",
      },
      {
        q: "Should I include an MBA on my product manager resume?",
        a: "Yes, but don't rely on it. An MBA supplements your experience — your resume should still lead with product achievements and impact metrics.",
      },
    ],
  },
  {
    slug: "mechanical-engineer",
    title: "Mechanical Engineer",
    category: "Technology",
    description:
      "Mechanical engineer resume example with CAD proficiency, manufacturing keywords, and design optimization achievements. ATS-optimized for engineering roles.",
    keywords: [
      "mechanical design",
      "CAD/CAM",
      "SolidWorks",
      "FEA",
      "GD&T",
      "manufacturing processes",
      "prototyping",
      "DFM/DFA",
      "thermal analysis",
      "project engineering",
    ],
    summary:
      "Mechanical engineer with 5+ years of experience in product design and manufacturing optimization. Redesigned critical assemblies that reduced production costs by 30% and improved product reliability, resulting in a 50% decrease in warranty claims.",
    experienceBullets: [
      "Redesigned 15+ mechanical assemblies using SolidWorks and FEA, reducing material costs by 30% while maintaining safety standards",
      "Led prototyping and testing of a new product line that generated $12M in first-year sales",
      "Implemented DFM/DFA principles that decreased manufacturing cycle time by 25% and reduced defect rates by 40%",
      "Conducted thermal and structural analyses using ANSYS, optimizing component performance and extending product life by 3 years",
      "Managed relationships with 8 suppliers, negotiating contracts that saved $800K annually on raw materials",
    ],
    skills: [
      "SolidWorks",
      "AutoCAD",
      "ANSYS",
      "MATLAB",
      "GD&T",
      "FEA/CFD",
      "3D Printing",
      "DFM/DFA",
      "Six Sigma",
      "Lean Manufacturing",
      "CNC Machining",
      "Technical Documentation",
    ],
    education: "Bachelor's in Mechanical Engineering",
    certifications: [
      "Certified SolidWorks Professional (CSWP)",
      "Six Sigma Green Belt",
    ],
    tips: [
      "List specific CAD software versions and simulation tools — 'SolidWorks 2024' and 'ANSYS Mechanical' are more ATS-friendly than generic terms.",
      "Quantify design improvements with cost savings, weight reduction percentages, or performance gains.",
      "Include manufacturing knowledge (CNC, injection molding, sheet metal) to show you understand production constraints.",
      "Mention any patents or patent-pending designs — these are strong differentiators for engineering roles.",
    ],
    faqs: [
      {
        q: "Should I include my senior design project on my resume?",
        a: "Yes, if you're within 3 years of graduation and the project is relevant. Describe it like a work project with scope, your role, tools used, and measurable outcomes.",
      },
      {
        q: "How important is CAD proficiency on a mechanical engineering resume?",
        a: "Critical. SolidWorks, AutoCAD, and CATIA are among the most common ATS keywords for ME roles. List your proficiency level and any certifications.",
      },
      {
        q: "Should I include GPA on my engineering resume?",
        a: "Include it if it's 3.2+ and you have less than 5 years of experience. After that, professional achievements carry much more weight.",
      },
    ],
  },
  {
    slug: "human-resources-manager",
    title: "Human Resources Manager",
    category: "Management",
    description:
      "HR manager resume example with talent acquisition keywords, employee engagement metrics, and compliance expertise. ATS-optimized for HR leadership roles.",
    keywords: [
      "talent acquisition",
      "employee engagement",
      "HRIS",
      "performance management",
      "compensation and benefits",
      "labor law compliance",
      "organizational development",
      "succession planning",
      "diversity and inclusion",
      "employee relations",
    ],
    summary:
      "Strategic HR manager with 8+ years of experience building high-performing teams and driving organizational development. Reduced turnover by 35% through data-driven engagement programs and scaled hiring from 50 to 200 employees in 18 months.",
    experienceBullets: [
      "Reduced employee turnover by 35% through implementation of engagement surveys, stay interviews, and career development programs",
      "Scaled company from 50 to 200 employees in 18 months, managing full-cycle recruitment across 6 departments",
      "Designed and launched a performance management system adopted by 500+ employees, increasing goal completion rates by 45%",
      "Led diversity and inclusion initiatives that increased underrepresented hiring by 40% and improved inclusion survey scores by 25%",
      "Ensured 100% compliance with federal and state labor laws through regular audits and updated employee handbook policies",
    ],
    skills: [
      "HRIS (Workday, BambooHR)",
      "Talent Acquisition",
      "Performance Management",
      "Compensation & Benefits",
      "Employee Relations",
      "Labor Law Compliance",
      "Organizational Development",
      "DEI Strategy",
      "Succession Planning",
      "Conflict Resolution",
      "ATS (Greenhouse, Lever)",
      "Change Management",
    ],
    education: "Bachelor's in Human Resources Management",
    certifications: [
      "SHRM-SCP",
      "PHR – Professional in Human Resources",
    ],
    tips: [
      "Include HRIS and ATS platforms you've used (Workday, Greenhouse, BambooHR) — these are critical HR tech keywords.",
      "Quantify HR impact with turnover rates, time-to-hire, engagement scores, and headcount growth metrics.",
      "Highlight both strategic HR (organizational design, succession planning) and operational HR (compliance, employee relations).",
      "SHRM-CP/SCP and PHR/SPHR certifications are strong differentiators — list them near your name.",
    ],
    faqs: [
      {
        q: "Is SHRM certification required for HR manager roles?",
        a: "Not always required, but strongly preferred for mid-senior roles. SHRM-CP/SCP or PHR/SPHR certifications demonstrate expertise and are commonly listed as preferred qualifications.",
      },
      {
        q: "How do I transition from HR generalist to HR manager?",
        a: "Highlight leadership experience: mentoring junior staff, leading projects, and managing vendor relationships. Quantify your impact on key HR metrics to demonstrate readiness for a management role.",
      },
      {
        q: "Should I include employee relations cases on my resume?",
        a: "Reference your ER experience in general terms ('Managed 50+ employee relations cases annually with 95% resolution rate') without disclosing confidential details.",
      },
    ],
  },
  {
    slug: "accountant",
    title: "Accountant",
    category: "Finance",
    description:
      "Accountant resume example with GAAP compliance keywords, financial reporting achievements, and audit experience. ATS-optimized for accounting and CPA roles.",
    keywords: [
      "GAAP",
      "financial reporting",
      "accounts payable/receivable",
      "general ledger",
      "tax preparation",
      "month-end close",
      "reconciliation",
      "audit",
      "QuickBooks",
      "ERP systems",
    ],
    summary:
      "Detail-oriented CPA with 5+ years of experience in financial reporting and tax compliance for mid-market companies. Reduced month-end close from 12 days to 5 days and identified $1.5M in tax savings through strategic planning.",
    experienceBullets: [
      "Managed month-end and year-end close processes for a $200M revenue company, reducing close cycle from 12 to 5 days",
      "Prepared and reviewed federal and state tax returns for 25+ entities, identifying $1.5M in tax savings through R&D credits",
      "Led the implementation of NetSuite ERP, migrating 5 years of financial data with zero discrepancies",
      "Performed balance sheet reconciliations for 40+ accounts and resolved $2M in aged discrepancies within first quarter",
      "Supported external audit process, preparing schedules and PBC lists that achieved zero audit adjustments for 3 consecutive years",
    ],
    skills: [
      "GAAP Compliance",
      "Tax Preparation",
      "NetSuite",
      "QuickBooks",
      "Excel (Advanced)",
      "General Ledger",
      "Month-End Close",
      "Financial Reporting",
      "Accounts Payable/Receivable",
      "Audit Support",
      "SAP",
      "Bank Reconciliation",
    ],
    education: "Bachelor's in Accounting",
    certifications: [
      "CPA – Certified Public Accountant",
      "QuickBooks ProAdvisor",
    ],
    tips: [
      "Put your CPA designation next to your name at the top of the resume — it's the most important credential for accounting roles.",
      "Mention specific ERP and accounting software (NetSuite, QuickBooks, SAP) as these are heavily filtered ATS keywords.",
      "Quantify efficiency improvements in the close process, audit preparation, or error reduction.",
      "Include both technical accounting skills (GAAP, tax) and soft skills (cross-department collaboration, process improvement).",
    ],
    faqs: [
      {
        q: "Is CPA required for accounting positions?",
        a: "Not for all roles, but it's strongly preferred for senior accountant, controller, and audit positions. If you're pursuing CPA, list 'CPA Candidate' or 'CPA Exam Passed' on your resume.",
      },
      {
        q: "How do I make an accounting resume stand out?",
        a: "Go beyond listing job duties. Quantify your impact: close cycle reduction, audit findings, tax savings identified, or process automation achievements.",
      },
      {
        q: "Should I include Big 4 experience even if it was entry-level?",
        a: "Absolutely. Big 4 experience carries significant weight in accounting. Include it even if you moved to industry — it signals rigorous training and high standards.",
      },
    ],
  },
  {
    slug: "ux-designer",
    title: "UX Designer",
    category: "Design",
    description:
      "UX designer resume example with user research keywords, usability testing achievements, and design system experience. ATS-optimized for UX/UI roles.",
    keywords: [
      "user experience design",
      "user research",
      "wireframing",
      "prototyping",
      "usability testing",
      "design systems",
      "information architecture",
      "interaction design",
      "accessibility",
      "Figma",
    ],
    summary:
      "User-centered UX designer with 5+ years of experience creating intuitive digital products for SaaS and e-commerce platforms. Led redesign efforts that improved task completion rates by 45% and increased user satisfaction scores by 30%.",
    experienceBullets: [
      "Led end-to-end UX redesign of the core SaaS platform, improving task completion rate by 45% and reducing support tickets by 35%",
      "Conducted 80+ user interviews and 20 usability studies to validate design decisions and prioritize feature development",
      "Built and maintained a design system with 120+ components used across 4 product teams, reducing design inconsistencies by 60%",
      "Designed accessible interfaces meeting WCAG 2.1 AA standards, expanding the product's addressable market by 15%",
      "Collaborated with engineering to implement design specifications with 95% fidelity, reducing post-launch design debt by 40%",
    ],
    skills: [
      "Figma",
      "Sketch",
      "Adobe XD",
      "User Research",
      "Wireframing",
      "Prototyping",
      "Usability Testing",
      "Design Systems",
      "Information Architecture",
      "Accessibility (WCAG)",
      "HTML/CSS",
      "Miro",
    ],
    education: "Bachelor's in Human-Computer Interaction",
    certifications: [
      "Google UX Design Certificate",
      "Nielsen Norman Group UX Certification",
    ],
    tips: [
      "Include a link to your UX portfolio — case studies showing your process (research > wireframes > testing > iteration) are essential.",
      "Highlight both quantitative metrics (conversion rates, task completion) and qualitative outcomes (user satisfaction, NPS scores).",
      "List specific research methods you've used (card sorting, tree testing, A/B testing) to demonstrate methodological rigor.",
      "Mention accessibility expertise (WCAG) — it's increasingly required and differentiates you from visual-only designers.",
    ],
    faqs: [
      {
        q: "Do I need to know how to code as a UX designer?",
        a: "Basic HTML/CSS knowledge is helpful and increasingly expected. It improves collaboration with developers. List it under skills if you have it, but focus your resume on design and research abilities.",
      },
      {
        q: "How should I structure my UX portfolio for the resume?",
        a: "Include 3-5 case studies showing your full design process. Each should cover the problem, your research, design iterations, and measurable outcomes. Link to it prominently on your resume.",
      },
      {
        q: "Is a degree required for UX design roles?",
        a: "Not strictly, but most companies prefer candidates with a relevant degree or bootcamp certificate. Strong portfolios can compensate for non-traditional backgrounds — pair yours with UX certifications.",
      },
    ],
  },
  {
    slug: "devops-engineer",
    title: "DevOps Engineer",
    category: "Technology",
    description:
      "DevOps engineer resume example with CI/CD keywords, infrastructure-as-code achievements, and cloud platform expertise. ATS-optimized for DevOps and SRE roles.",
    keywords: [
      "CI/CD",
      "infrastructure as code",
      "cloud computing",
      "containerization",
      "monitoring",
      "automation",
      "Kubernetes",
      "Terraform",
      "Linux administration",
      "site reliability engineering",
    ],
    summary:
      "DevOps engineer with 5+ years of experience building and maintaining cloud infrastructure at scale. Reduced deployment frequency from monthly to 50+ daily deployments while maintaining 99.99% uptime across production environments.",
    experienceBullets: [
      "Architected multi-region AWS infrastructure using Terraform, achieving 99.99% uptime and supporting 10M+ monthly active users",
      "Built CI/CD pipelines in GitHub Actions and Jenkins that enabled 50+ daily deployments with zero-downtime releases",
      "Migrated 40+ microservices from EC2 to Kubernetes (EKS), reducing infrastructure costs by 45% and improving scalability",
      "Implemented comprehensive monitoring with Datadog and PagerDuty, reducing mean time to detection from 15 minutes to 90 seconds",
      "Automated infrastructure provisioning with Terraform and Ansible, reducing environment setup time from 2 days to 30 minutes",
    ],
    skills: [
      "AWS",
      "Terraform",
      "Kubernetes",
      "Docker",
      "Jenkins",
      "GitHub Actions",
      "Linux",
      "Python",
      "Bash",
      "Datadog",
      "Prometheus/Grafana",
      "Ansible",
    ],
    education: "Bachelor's in Computer Science",
    certifications: [
      "AWS Certified DevOps Engineer – Professional",
      "Certified Kubernetes Administrator (CKA)",
      "HashiCorp Terraform Associate",
    ],
    tips: [
      "Quantify reliability metrics — uptime percentages, MTTR, deployment frequency, and change failure rates are key DevOps indicators.",
      "List specific cloud services (EC2, S3, Lambda) rather than just 'AWS' for better ATS keyword matching.",
      "Include both IaC tools (Terraform, CloudFormation) and configuration management tools (Ansible, Chef) you've used.",
      "Mention cost optimization achievements — reducing cloud spend is a high-value DevOps contribution.",
    ],
    faqs: [
      {
        q: "What's the difference between a DevOps engineer and SRE resume?",
        a: "DevOps resumes emphasize CI/CD, automation, and IaC. SRE resumes focus more on reliability, incident response, and SLO/SLA management. Tailor your resume to the specific role title.",
      },
      {
        q: "Which cloud certifications are most valuable for DevOps?",
        a: "AWS Certified DevOps Engineer Professional and CKA are the most recognized. Start with an associate-level cloud certification if you're early in your career.",
      },
      {
        q: "Should I include scripting projects on a DevOps resume?",
        a: "Yes — automation scripts and tools you've built demonstrate practical skills. Describe the problem they solved and the time/effort saved, e.g., 'Built Python script that automated log rotation, saving 5 hours/week.'",
      },
    ],
  },
  {
    slug: "physical-therapist",
    title: "Physical Therapist",
    category: "Healthcare",
    description:
      "Physical therapist resume example with clinical keywords, patient outcomes, and treatment specialization. ATS-optimized for PT positions in clinics and hospitals.",
    keywords: [
      "physical therapy",
      "patient assessment",
      "treatment planning",
      "manual therapy",
      "therapeutic exercise",
      "rehabilitation",
      "documentation",
      "patient education",
      "functional outcomes",
      "evidence-based practice",
    ],
    summary:
      "Licensed physical therapist with 6+ years of outpatient orthopedic experience. Maintains a 95% patient satisfaction rate and consistently achieves functional outcome scores 20% above clinic benchmarks through evidence-based treatment protocols.",
    experienceBullets: [
      "Managed a caseload of 50+ patients weekly across orthopedic, post-surgical, and sports rehabilitation specialties",
      "Achieved functional outcome scores 20% above clinic average through individualized evidence-based treatment plans",
      "Reduced average treatment duration by 15% while maintaining outcome quality, improving clinic revenue per patient",
      "Mentored 8 DPT students and 3 PTAs, developing training protocols that improved their clinical readiness assessments by 30%",
      "Implemented a fall prevention program for geriatric patients that reduced fall-related re-admissions by 40%",
    ],
    skills: [
      "Manual Therapy",
      "Therapeutic Exercise",
      "Orthopedic Rehabilitation",
      "Sports Rehabilitation",
      "Gait Analysis",
      "Dry Needling",
      "Patient Education",
      "EMR Documentation",
      "Functional Assessment",
      "Neuromuscular Re-education",
      "Modalities",
      "Evidence-Based Practice",
    ],
    education: "Doctor of Physical Therapy (DPT)",
    certifications: [
      "Licensed Physical Therapist",
      "OCS – Orthopedic Clinical Specialist",
      "Certified Dry Needling Practitioner",
    ],
    tips: [
      "List your PT license, state, and any board certifications (OCS, SCS, NCS) at the top of your resume.",
      "Quantify patient outcomes with functional score improvements, discharge rates, and satisfaction metrics.",
      "Include specialty areas (orthopedic, neurological, pediatric) and treatment techniques (manual therapy, dry needling).",
      "Mention EMR systems (WebPT, Net Health) and documentation standards for ATS matching.",
    ],
    faqs: [
      {
        q: "How important is specialization on a PT resume?",
        a: "Very important for competitive roles. Board certifications like OCS (Orthopedics) or SCS (Sports) command higher salaries and signal expertise. Even without certification, highlighting a specialty area helps.",
      },
      {
        q: "Should I list continuing education courses?",
        a: "Include notable CE that's relevant to the role (e.g., certified dry needling, McKenzie method). Don't list every course — focus on specialized skills that differentiate you.",
      },
      {
        q: "How do I handle a resume for travel PT positions?",
        a: "List each assignment with the facility, location, and dates. Emphasize adaptability, quick ramp-up time, and multi-setting experience. Include all active state licenses.",
      },
    ],
  },
  {
    slug: "content-marketing-specialist",
    title: "Content Marketing Specialist",
    category: "Marketing",
    description:
      "Content marketing specialist resume example with SEO keywords, content strategy achievements, and traffic growth metrics. ATS-optimized for content roles.",
    keywords: [
      "content strategy",
      "SEO writing",
      "content calendar",
      "blog management",
      "copywriting",
      "content analytics",
      "email marketing",
      "social media content",
      "editorial planning",
      "lead generation content",
    ],
    summary:
      "Creative content marketing specialist with 4+ years of experience driving organic growth through strategic content programs. Built a blog from 0 to 150K monthly visitors and generated 2,500+ marketing qualified leads per month through SEO-optimized content.",
    experienceBullets: [
      "Built and scaled a company blog from 0 to 150K monthly organic visitors within 18 months through keyword research and SEO optimization",
      "Created 200+ pieces of content (blog posts, whitepapers, case studies) generating 2,500+ MQLs per month",
      "Developed content strategy that ranked 50+ pages on Google's first page for competitive industry keywords",
      "Managed a content calendar and coordinated with 10+ subject matter experts to produce consistent weekly output",
      "Increased email newsletter subscribers by 300% and improved open rates from 18% to 32% through content-driven campaigns",
    ],
    skills: [
      "SEO Writing",
      "Content Strategy",
      "WordPress",
      "Semrush",
      "Ahrefs",
      "Google Analytics",
      "Copywriting",
      "Email Marketing",
      "HubSpot",
      "Social Media Marketing",
      "Content Calendar Management",
      "A/B Testing",
    ],
    education: "Bachelor's in English or Communications",
    certifications: [
      "HubSpot Content Marketing Certification",
      "Semrush SEO Toolkit Certification",
    ],
    tips: [
      "Include traffic growth metrics, keyword rankings, and lead generation numbers — content marketers must prove ROI.",
      "List specific SEO tools (Semrush, Ahrefs, Moz) and CMS platforms (WordPress, HubSpot) for ATS matching.",
      "Showcase content variety — blog posts, case studies, whitepapers, and video scripts demonstrate range.",
      "Include links to published work or your personal blog to demonstrate writing quality.",
    ],
    faqs: [
      {
        q: "Should I include a writing portfolio on my resume?",
        a: "Absolutely. Include 3-5 links to your best published pieces, ideally ones with measurable results (high traffic, conversions). A portfolio is as important as your resume for content roles.",
      },
      {
        q: "How do I show SEO skills on a content marketing resume?",
        a: "Mention keyword research tools (Semrush, Ahrefs), include ranking improvements ('ranked 50 pages on page 1'), and note on-page SEO techniques you've implemented (meta tags, internal linking, schema markup).",
      },
      {
        q: "Is a marketing degree required for content marketing roles?",
        a: "Not necessarily. English, journalism, and communications degrees are equally valued. Demonstrate strong writing skills, SEO knowledge, and marketing analytics — these matter more than the specific degree.",
      },
    ],
  },
  {
    slug: "business-analyst",
    title: "Business Analyst",
    category: "Data & Analytics",
    description:
      "Business analyst resume example with requirements gathering keywords, process improvement achievements, and stakeholder management. ATS-optimized for BA roles.",
    keywords: [
      "requirements gathering",
      "business process analysis",
      "stakeholder management",
      "use cases",
      "user stories",
      "gap analysis",
      "data analysis",
      "process improvement",
      "UAT",
      "documentation",
    ],
    summary:
      "Certified business analyst with 5+ years of experience bridging business needs and technology solutions. Delivered 20+ projects that streamlined operations, reducing process cycle times by 40% and saving $3M+ annually across the organization.",
    experienceBullets: [
      "Gathered and documented requirements for 20+ projects valued at $15M+, achieving 98% stakeholder sign-off on first review",
      "Identified and mapped process inefficiencies that led to $3M+ in annual cost savings across 4 business units",
      "Created detailed user stories and acceptance criteria that reduced development rework by 30%",
      "Facilitated UAT sessions with 50+ business users, achieving 100% defect resolution before go-live for 3 major releases",
      "Developed as-is and to-be process flows using Visio and Lucidchart, enabling executive alignment on digital transformation initiatives",
    ],
    skills: [
      "Requirements Gathering",
      "JIRA",
      "Confluence",
      "SQL",
      "Visio",
      "User Story Writing",
      "Process Mapping",
      "UAT Coordination",
      "Stakeholder Management",
      "Agile/Scrum",
      "Data Analysis",
      "Lucidchart",
    ],
    education: "Bachelor's in Business Administration or Information Systems",
    certifications: [
      "CBAP – Certified Business Analysis Professional",
      "Certified ScrumMaster (CSM)",
      "IIBA Entry Certificate in Business Analysis (ECBA)",
    ],
    tips: [
      "Emphasize your ability to translate business needs into technical requirements — this is the core BA skill.",
      "Include tools for documentation (Jira, Confluence), process mapping (Visio), and data analysis (SQL, Excel).",
      "Quantify your impact with cost savings, cycle time reductions, and stakeholder satisfaction metrics.",
      "Mention specific methodologies (Agile, Waterfall, hybrid) and your role in each.",
    ],
    faqs: [
      {
        q: "What's the difference between a business analyst and data analyst resume?",
        a: "Business analyst resumes focus on requirements gathering, process improvement, and stakeholder management. Data analyst resumes emphasize SQL, statistics, and data visualization. Tailor yours to the specific job title.",
      },
      {
        q: "Is CBAP certification worth getting?",
        a: "Yes, for mid-senior roles. CBAP requires 7,500 hours of BA experience and demonstrates deep expertise. For junior BAs, start with ECBA or PMI-PBA.",
      },
      {
        q: "Should I include technical skills on a business analyst resume?",
        a: "Yes — SQL, JIRA, Confluence, and Visio are expected. If you have Python, Tableau, or advanced Excel skills, include them to stand out from other BA candidates.",
      },
    ],
  },
  {
    slug: "full-stack-developer",
    title: "Full Stack Developer",
    category: "Technology",
    description:
      "Full stack developer resume example with front-end and back-end keywords, deployment achievements, and modern framework expertise. ATS-optimized for developer roles.",
    keywords: [
      "full stack development",
      "front-end development",
      "back-end development",
      "React",
      "Node.js",
      "REST APIs",
      "database design",
      "responsive design",
      "cloud deployment",
      "agile development",
    ],
    summary:
      "Versatile full stack developer with 4+ years of experience building end-to-end web applications using React, Node.js, and PostgreSQL. Shipped features serving 1M+ users and reduced page load times by 60% through performance optimization.",
    experienceBullets: [
      "Built and deployed 8+ full-stack web applications using React, Node.js, and PostgreSQL, serving 1M+ monthly active users",
      "Reduced page load times by 60% through code splitting, image optimization, and server-side rendering implementation",
      "Designed and implemented RESTful APIs handling 500K+ daily requests with 99.9% uptime and sub-100ms response times",
      "Led front-end migration from jQuery to React, improving developer productivity by 40% and reducing UI bugs by 55%",
      "Implemented automated testing suite (Jest, Cypress) achieving 85% code coverage and reducing production bugs by 70%",
    ],
    skills: [
      "React",
      "Next.js",
      "TypeScript",
      "Node.js",
      "Express",
      "PostgreSQL",
      "MongoDB",
      "REST APIs",
      "GraphQL",
      "Docker",
      "AWS",
      "Git",
    ],
    education: "Bachelor's in Computer Science",
    certifications: [
      "AWS Certified Developer – Associate",
      "Meta Front-End Developer Certificate",
    ],
    tips: [
      "Clearly list both front-end and back-end technologies to signal true full-stack capability to ATS systems.",
      "Include database experience (SQL and NoSQL) as it's a key differentiator between front-end and full-stack developers.",
      "Showcase deployment and DevOps skills (Docker, CI/CD, cloud) to demonstrate you can own features end-to-end.",
      "Link to your GitHub profile with active repositories that demonstrate code quality and diverse technology usage.",
    ],
    faqs: [
      {
        q: "Should I specialize or stay full stack?",
        a: "Both paths are viable. Full stack developers are valued at startups and smaller companies. Specialists often command higher salaries at larger companies. Your resume should reflect the role you're targeting.",
      },
      {
        q: "How do I list projects vs. work experience?",
        a: "Prioritize professional experience. Include a 'Projects' section below work experience for notable open-source contributions or side projects that demonstrate skills not covered by your job history.",
      },
      {
        q: "Is a CS degree required for full stack developer roles?",
        a: "Not required, but helpful. Bootcamp graduates and self-taught developers are widely hired. Compensate with a strong portfolio, relevant certifications, and demonstrated ability to ship production code.",
      },
    ],
  },
  {
    slug: "cybersecurity-analyst",
    title: "Cybersecurity Analyst",
    category: "Technology",
    description:
      "Cybersecurity analyst resume example with threat detection keywords, incident response achievements, and security certifications. ATS-optimized for infosec roles.",
    keywords: [
      "threat detection",
      "incident response",
      "vulnerability assessment",
      "SIEM",
      "network security",
      "penetration testing",
      "security operations",
      "compliance",
      "risk assessment",
      "endpoint security",
    ],
    summary:
      "Cybersecurity analyst with 4+ years of experience in threat detection, incident response, and vulnerability management. Investigated 500+ security incidents with a 98% resolution rate and reduced mean time to respond from 4 hours to 45 minutes.",
    experienceBullets: [
      "Investigated and resolved 500+ security incidents with 98% resolution rate, reducing MTTR from 4 hours to 45 minutes",
      "Conducted vulnerability assessments across 2,000+ endpoints, remediating 95% of critical vulnerabilities within SLA",
      "Implemented SIEM rules and playbooks in Splunk that increased threat detection accuracy by 60% and reduced false positives by 40%",
      "Led phishing simulation program that reduced employee click-through rates from 25% to 5% over 12 months",
      "Performed penetration testing on web applications, identifying 30+ critical vulnerabilities before production deployment",
    ],
    skills: [
      "Splunk",
      "CrowdStrike",
      "Wireshark",
      "Nessus",
      "Burp Suite",
      "SIEM Management",
      "Incident Response",
      "Vulnerability Scanning",
      "Firewall Management",
      "Python Scripting",
      "NIST Framework",
      "SOC Operations",
    ],
    education: "Bachelor's in Cybersecurity or Computer Science",
    certifications: [
      "CompTIA Security+",
      "Certified Ethical Hacker (CEH)",
      "GIAC Security Essentials (GSEC)",
    ],
    tips: [
      "List security tools by name (Splunk, CrowdStrike, Nessus) — generic terms like 'SIEM experience' are less effective for ATS.",
      "Include compliance frameworks you've worked with (NIST, SOC 2, ISO 27001, PCI-DSS) as these are frequently required.",
      "Quantify your incident response metrics — MTTR, incidents investigated, vulnerabilities remediated, and false positive reduction.",
      "Security certifications (Security+, CEH, CISSP) are critical differentiators — list them prominently.",
    ],
    faqs: [
      {
        q: "Which cybersecurity certification should I get first?",
        a: "Start with CompTIA Security+ — it's the most widely recognized entry-level security certification. From there, pursue CEH or GIAC certifications based on whether you prefer offensive or defensive security.",
      },
      {
        q: "How do I break into cybersecurity with no experience?",
        a: "Start with Security+ certification, build a home lab, participate in CTF competitions, and contribute to open-source security projects. An IT helpdesk or sysadmin role is a common stepping stone.",
      },
      {
        q: "Should I include CTF competitions on my resume?",
        a: "Yes, especially early in your career. CTF achievements demonstrate practical skills and passion for security. Include notable placements and platforms (HackTheBox, TryHackMe).",
      },
    ],
  },
  {
    slug: "operations-manager",
    title: "Operations Manager",
    category: "Management",
    description:
      "Operations manager resume example with process optimization keywords, supply chain achievements, and leadership metrics. ATS-optimized for operations roles.",
    keywords: [
      "operations management",
      "process optimization",
      "supply chain management",
      "lean manufacturing",
      "inventory management",
      "P&L responsibility",
      "vendor management",
      "quality assurance",
      "team leadership",
      "KPI tracking",
    ],
    summary:
      "Results-oriented operations manager with 8+ years of experience optimizing processes and leading teams of 50+ across manufacturing and logistics. Achieved $4M in annual cost savings through Lean Six Sigma initiatives and improved on-time delivery from 82% to 97%.",
    experienceBullets: [
      "Managed daily operations for a $40M facility with 50+ direct reports across production, logistics, and quality departments",
      "Led Lean Six Sigma initiatives that generated $4M in annual cost savings through waste reduction and process optimization",
      "Improved on-time delivery rate from 82% to 97% by redesigning production scheduling and inventory management systems",
      "Negotiated vendor contracts saving $1.2M annually while maintaining quality standards and delivery timelines",
      "Implemented KPI dashboards that provided real-time visibility into operational metrics, enabling data-driven decision-making",
    ],
    skills: [
      "Lean Six Sigma",
      "Supply Chain Management",
      "P&L Management",
      "ERP Systems (SAP)",
      "Inventory Management",
      "Vendor Negotiation",
      "Process Improvement",
      "Team Leadership",
      "KPI Development",
      "Quality Assurance",
      "Budgeting",
      "Safety Compliance",
    ],
    education: "Bachelor's in Operations Management or Business Administration",
    certifications: [
      "Lean Six Sigma Black Belt",
      "APICS Certified Supply Chain Professional (CSCP)",
    ],
    tips: [
      "Lead with P&L scope and team size to immediately communicate your level of responsibility.",
      "Quantify operational improvements with cost savings, efficiency gains, and delivery metrics.",
      "Include Lean/Six Sigma methodology and belt level — these are common filter criteria for operations roles.",
      "Mention specific ERP systems (SAP, Oracle) and inventory management tools for ATS matching.",
    ],
    faqs: [
      {
        q: "How do I transition from individual contributor to operations manager?",
        a: "Highlight informal leadership: mentoring, leading projects, and process improvements you initiated. Quantify the impact of these contributions to demonstrate management readiness.",
      },
      {
        q: "Is Six Sigma certification important for operations roles?",
        a: "Yes — Lean Six Sigma Green Belt or Black Belt is preferred for most mid-senior operations roles. It demonstrates a structured approach to process improvement that employers value.",
      },
      {
        q: "Should I include safety and compliance on my resume?",
        a: "Absolutely. OSHA compliance, safety record improvements, and regulatory adherence are critical operational metrics. Include incident rate reductions and audit results.",
      },
    ],
  },
  {
    slug: "social-media-manager",
    title: "Social Media Manager",
    category: "Marketing",
    description:
      "Social media manager resume example with engagement metrics, content creation keywords, and platform expertise. ATS-optimized for social media roles.",
    keywords: [
      "social media management",
      "content creation",
      "community engagement",
      "social media analytics",
      "paid social",
      "influencer marketing",
      "brand voice",
      "content calendar",
      "social listening",
      "platform strategy",
    ],
    summary:
      "Creative social media manager with 4+ years of experience growing brand presence across major platforms. Built Instagram following from 5K to 250K organically and drove $1.5M in attributed revenue through strategic social campaigns.",
    experienceBullets: [
      "Grew Instagram following from 5K to 250K organically in 24 months through consistent content strategy and community engagement",
      "Managed $500K annual paid social budget across Meta, TikTok, and LinkedIn, achieving 5.2x average ROAS",
      "Created and executed influencer marketing program with 40+ creators, generating 15M+ impressions and $1.5M in attributed revenue",
      "Developed brand voice guidelines and content playbooks adopted across 3 global markets",
      "Increased LinkedIn engagement rate by 400% through a thought leadership content series featuring executive team members",
    ],
    skills: [
      "Instagram",
      "TikTok",
      "LinkedIn",
      "Meta Business Suite",
      "Hootsuite",
      "Sprout Social",
      "Canva",
      "Adobe Creative Suite",
      "Paid Social Advertising",
      "Influencer Management",
      "Community Management",
      "Social Analytics",
    ],
    education: "Bachelor's in Marketing or Communications",
    certifications: [
      "Meta Certified Digital Marketing Associate",
      "Hootsuite Social Marketing Certification",
    ],
    tips: [
      "Include platform-specific metrics — follower growth, engagement rates, and ROAS for each major platform you manage.",
      "List social media management tools (Hootsuite, Sprout Social, Buffer) and advertising platforms (Meta Ads, TikTok Ads).",
      "Showcase both organic growth and paid social experience to demonstrate well-rounded expertise.",
      "Include examples of crisis management or community engagement to show strategic thinking beyond content creation.",
    ],
    faqs: [
      {
        q: "How do I show ROI on a social media resume?",
        a: "Connect social metrics to business outcomes: attributed revenue from social campaigns, leads generated, traffic driven to website, and conversion rates from social channels. Use UTM tracking data if available.",
      },
      {
        q: "Should I include my personal social media accounts?",
        a: "Only if they demonstrate professional-level content creation and significant followings. A personal TikTok with 50K+ followers shows practical expertise. Ensure all content is brand-safe.",
      },
      {
        q: "Is social media management a viable long-term career?",
        a: "Yes — social media managers can advance to Director of Social, Head of Content, or VP of Marketing. Emphasize strategic skills (budget management, team leadership, brand strategy) as you grow.",
      },
    ],
  },
  {
    slug: "civil-engineer",
    title: "Civil Engineer",
    category: "Technology",
    description:
      "Civil engineer resume example with structural design keywords, project management achievements, and PE license details. ATS-optimized for civil engineering roles.",
    keywords: [
      "civil engineering",
      "structural design",
      "AutoCAD Civil 3D",
      "project management",
      "site development",
      "construction management",
      "permitting",
      "environmental compliance",
      "surveying",
      "infrastructure design",
    ],
    summary:
      "Licensed PE civil engineer with 7+ years of experience in structural design and infrastructure projects. Managed $25M+ in construction projects delivered on time and within budget, with zero safety incidents across 500K+ labor hours.",
    experienceBullets: [
      "Managed design and construction oversight for $25M+ infrastructure projects including bridges, roadways, and water systems",
      "Prepared structural calculations and construction documents for 40+ commercial and residential projects with zero code violations",
      "Led permitting process for a $15M mixed-use development, securing all approvals 3 weeks ahead of schedule",
      "Implemented BIM workflows that reduced design conflicts by 50% and saved $800K in change orders during construction",
      "Supervised field inspection of 30+ active construction sites, maintaining zero safety incidents across 500K+ labor hours",
    ],
    skills: [
      "AutoCAD Civil 3D",
      "Revit",
      "Structural Analysis",
      "BIM",
      "Project Management",
      "Construction Management",
      "Environmental Compliance",
      "Geotechnical Engineering",
      "Stormwater Management",
      "Site Design",
      "Permitting",
      "Cost Estimation",
    ],
    education: "Bachelor's in Civil Engineering",
    certifications: [
      "Professional Engineer (PE) License",
      "LEED AP",
      "Engineer in Training (EIT/FE)",
    ],
    tips: [
      "Include your PE license with state and license number — it's the most critical credential for civil engineering roles.",
      "List specific design software (AutoCAD Civil 3D, Revit, MicroStation) and analysis tools (STAAD, RISA) for ATS matching.",
      "Quantify project scope with dollar values, square footage, and team sizes to demonstrate experience level.",
      "Include LEED or sustainable design experience — green building expertise is increasingly valued.",
    ],
    faqs: [
      {
        q: "Is a PE license required for civil engineering roles?",
        a: "For senior roles and any position involving stamping/sealing drawings, yes. Many companies require PE for promotion beyond mid-level. If you have your FE/EIT, mention it and your expected PE timeline.",
      },
      {
        q: "How do I describe large team projects where I was one contributor?",
        a: "Focus on your specific contributions: 'Designed the foundation system for a $30M commercial building' is more impactful than 'Worked on a team that built a commercial building.'",
      },
      {
        q: "Should I include field experience on a design-focused resume?",
        a: "Yes — field experience (construction oversight, site inspections) makes you a better designer and shows you understand constructibility. Include it even if your target role is office-based.",
      },
    ],
  },
  {
    slug: "data-scientist",
    title: "Data Scientist",
    category: "Data & Analytics",
    description:
      "Data scientist resume example with machine learning keywords, model performance metrics, and Python expertise. ATS-optimized for DS and ML roles.",
    keywords: [
      "machine learning",
      "Python",
      "statistical modeling",
      "deep learning",
      "natural language processing",
      "data pipelines",
      "A/B testing",
      "feature engineering",
      "model deployment",
      "predictive analytics",
    ],
    summary:
      "Data scientist with 5+ years of experience building production ML models that drive business decisions. Developed a recommendation engine that increased user engagement by 35% and a fraud detection model saving $10M+ annually.",
    experienceBullets: [
      "Built a recommendation engine using collaborative filtering and deep learning that increased user engagement by 35% and revenue by $8M",
      "Developed real-time fraud detection model (XGBoost + neural network ensemble) that saved $10M+ annually with 99.2% precision",
      "Designed and deployed NLP pipeline for customer feedback analysis, processing 1M+ reviews and reducing manual categorization by 90%",
      "Led A/B testing framework development that enabled 100+ concurrent experiments, accelerating product iteration by 3x",
      "Mentored 3 junior data scientists and established ML model governance standards adopted across the data organization",
    ],
    skills: [
      "Python",
      "TensorFlow",
      "PyTorch",
      "Scikit-learn",
      "SQL",
      "Spark",
      "AWS SageMaker",
      "MLflow",
      "Feature Engineering",
      "NLP",
      "Deep Learning",
      "Statistical Modeling",
    ],
    education: "Master's in Data Science or Statistics",
    certifications: [
      "AWS Certified Machine Learning – Specialty",
      "Google Professional Machine Learning Engineer",
    ],
    tips: [
      "Highlight model performance metrics (precision, recall, AUC) alongside business impact (revenue, cost savings) for each project.",
      "List both ML frameworks (TensorFlow, PyTorch) and deployment tools (MLflow, SageMaker) to show end-to-end capability.",
      "Include experience with large-scale data processing tools (Spark, Hadoop) if applicable — scale matters for DS roles.",
      "Mention publications, patents, or Kaggle rankings if you have them — they're strong signals for data science roles.",
    ],
    faqs: [
      {
        q: "Do I need a PhD for data scientist roles?",
        a: "Not for most industry roles. A Master's degree is typically sufficient, and many companies hire strong candidates with Bachelor's degrees and practical experience. A PhD is more important for research-focused roles.",
      },
      {
        q: "How do I show ML model impact on a resume?",
        a: "Pair technical metrics (F1 score, AUC, latency) with business outcomes (revenue increase, cost reduction, time saved). 'Built a churn prediction model (AUC 0.92) that reduced churn by 15%, saving $3M annually' is ideal.",
      },
      {
        q: "Should I include Kaggle projects on my resume?",
        a: "Yes, especially if you have top placements. 'Kaggle Competition — Top 5% (Gold Medal) in [competition name]' demonstrates practical ML skills and competitive drive.",
      },
    ],
  },
  {
    slug: "executive-assistant",
    title: "Executive Assistant",
    category: "Management",
    description:
      "Executive assistant resume example with calendar management keywords, executive support achievements, and organizational skills. ATS-optimized for EA roles.",
    keywords: [
      "executive support",
      "calendar management",
      "travel coordination",
      "meeting preparation",
      "correspondence",
      "confidential information",
      "event planning",
      "expense reporting",
      "stakeholder communication",
      "office management",
    ],
    summary:
      "Highly organized executive assistant with 6+ years of experience supporting C-suite executives at Fortune 500 companies. Managed calendars with 50+ weekly meetings, coordinated $200K+ in annual travel, and streamlined administrative processes saving 15 hours per week.",
    experienceBullets: [
      "Provided comprehensive support to CEO and 3 SVPs, managing calendars with 50+ weekly meetings across 4 time zones",
      "Coordinated $200K+ in annual executive travel including international itineraries, visa processing, and expense reconciliation",
      "Planned and executed 20+ corporate events annually (board meetings, offsites, conferences) for up to 500 attendees",
      "Streamlined expense reporting process using Concur, reducing approval cycle from 2 weeks to 3 days",
      "Served as primary liaison between executive team and 200+ employees, managing sensitive communications with discretion",
    ],
    skills: [
      "Microsoft Office Suite",
      "Google Workspace",
      "Calendar Management",
      "Travel Coordination",
      "Event Planning",
      "Concur",
      "Expense Management",
      "Meeting Coordination",
      "Document Management",
      "Stakeholder Communication",
      "Discretion & Confidentiality",
      "Project Coordination",
    ],
    education: "Bachelor's in Business Administration",
    certifications: [
      "Certified Administrative Professional (CAP)",
      "Microsoft Office Specialist (MOS)",
    ],
    tips: [
      "Specify the executive level you've supported (CEO, C-suite, VP) — this immediately signals your experience level.",
      "Quantify your scope: number of executives supported, meetings managed per week, travel budget coordinated.",
      "Highlight technology proficiency — Microsoft Office, Google Workspace, Concur, and any project management tools.",
      "Emphasize discretion and confidentiality handling — these are non-negotiable EA requirements.",
    ],
    faqs: [
      {
        q: "How do I make an executive assistant resume stand out?",
        a: "Quantify everything: meetings managed, travel budgets coordinated, events planned, and time saved through process improvements. Show that you're a strategic partner, not just an administrator.",
      },
      {
        q: "Should I include software skills on an EA resume?",
        a: "Absolutely. List specific tools: Microsoft Office (advanced Excel, PowerPoint), Google Workspace, Slack, Zoom, Concur, and any CRM or project management tools you've used.",
      },
      {
        q: "Is certification important for executive assistant roles?",
        a: "CAP certification is valued but not required. It demonstrates professional commitment and can justify higher compensation. If you have it, list it prominently.",
      },
    ],
  },
]

export function getExampleBySlug(slug: string): ResumeExample | undefined {
  return resumeExamples.find((e) => e.slug === slug)
}
